hw_sha: Fix coding style errors
Checkpatch complains about:

 ERROR: "foo * bar" should be "foo *bar"

and

 CHECK: Alignment should match open parenthesis

(cherry picked from commit ba139783110a1a6aee1b60d091744a26ecad4806)
Signed-off-by: Joel Stanley <joel@jms.id.au>